from typing import Protocol

from backend.domain import CardInstallment, CardInvoice, CardPurchase, CreditCard


class CreditCardRepository(Protocol):
    def list_all(self) -> list[CreditCard]: ...
    def get(self, card_id: str) -> CreditCard | None: ...
    def save(self, card: CreditCard) -> CreditCard: ...
    def delete(self, card_id: str) -> bool: ...


class CardPurchaseRepository(Protocol):
    def list_all(self) -> list[CardPurchase]: ...
    def get(self, purchase_id: str) -> CardPurchase | None: ...
    def save(self, purchase: CardPurchase) -> CardPurchase: ...
    def delete(self, purchase_id: str) -> bool: ...


class CardInstallmentRepository(Protocol):
    def list_by_card(self, card_id: str) -> list[CardInstallment]: ...
    def list_by_invoice(self, card_id: str, reference_month: str) -> list[CardInstallment]: ...
    def save_all(self, installments: list[CardInstallment]) -> list[CardInstallment]: ...
    def delete_by_purchase(self, purchase_id: str) -> int: ...


class CardInvoiceRepository(Protocol):
    def list_by_card(self, card_id: str) -> list[CardInvoice]: ...
    def get(self, card_id: str, reference_month: str) -> CardInvoice | None: ...
    def save(self, invoice: CardInvoice) -> CardInvoice: ...
