from typing import Protocol

from backend.domain import RecurringExpense


class RecurringExpenseRepository(Protocol):
    def list_all(self) -> list[RecurringExpense]: ...
    def get(self, expense_id: str) -> RecurringExpense | None: ...
    def save(self, expense: RecurringExpense) -> RecurringExpense: ...
    def delete(self, expense_id: str) -> bool: ...
