from typing import Protocol

from backend.domain import Transaction


class TransactionRepository(Protocol):
    """Porta de persistência para lançamentos financeiros."""

    def list_all(self) -> list[Transaction]: ...

    def get(self, transaction_id: str) -> Transaction | None: ...

    def save(self, transaction: Transaction) -> Transaction: ...

    def save_all(self, transactions: list[Transaction]) -> list[Transaction]: ...

    def delete(self, transaction_id: str) -> bool: ...

    def delete_by_account(self, account_id: str) -> int: ...

    def delete_by_installment_group(self, group_id: str) -> int: ...
