import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { api } from '../api/client'
import type { Account, CardInvoice, CardInvoiceDetail, CardPurchaseWrite, Category, CreditCard, CreditCardWrite } from '../api/types'
import { ConfirmDialog } from '../components/ConfirmDialog'
import './AccountsPage.css'
import './CardsPage.css'
import './CardInvoiceActions.css'

const currency = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
const dateFormat = new Intl.DateTimeFormat('pt-BR')
const today = () => new Date().toISOString().slice(0, 10)
const emptyCard = (accountId = ''): CreditCardWrite => ({ name: '', credit_limit: 0, closing_day: 1, due_day: 10, payment_account_id: accountId, active: true })
const emptyPurchase = (): CardPurchaseWrite => ({ category_id: '', description: '', purchase_date: today(), total_amount: 0, installments: 1 })

export function CardsPage() {
  const [cards, setCards] = useState<CreditCard[]>([]), [accounts, setAccounts] = useState<Account[]>([]), [categories, setCategories] = useState<Category[]>([])
  const [selectedId, setSelectedId] = useState<string | null>(null), [invoices, setInvoices] = useState<CardInvoice[]>([]), [detail, setDetail] = useState<CardInvoiceDetail | null>(null)
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState<string | null>(null)
  const [cardOpen, setCardOpen] = useState(false), [purchaseOpen, setPurchaseOpen] = useState(false), [editing, setEditing] = useState<CreditCard | null>(null), [confirmExit, setConfirmExit] = useState<'card' | 'purchase' | null>(null)
  const [invoiceAction, setInvoiceAction] = useState<{ kind: 'close' | 'pay'; invoice: CardInvoice } | null>(null)
  const [cardForm, setCardForm] = useState<CreditCardWrite>(emptyCard()), [cardInitial, setCardInitial] = useState<CreditCardWrite | null>(null)
  const [purchaseForm, setPurchaseForm] = useState<CardPurchaseWrite>(emptyPurchase()), [purchaseInitial, setPurchaseInitial] = useState<CardPurchaseWrite | null>(null)
  const selected = cards.find((card) => card.id === selectedId) ?? null

  const load = useCallback(async () => {
    setLoading(true); setError(null)
    try {
      const [cardData, accountData, categoryData] = await Promise.all([api.creditCards.list(), api.accounts.list(), api.categories.list()])
      setCards(cardData); setAccounts(accountData); setCategories(categoryData.filter((item) => item.type === 'Despesa'))
      setSelectedId((current) => current && cardData.some((card) => card.id === current) ? current : cardData[0]?.id ?? null)
    } catch (requestError) { setError(messageFrom(requestError)) } finally { setLoading(false) }
  }, [])
  // oxlint-disable-next-line react/set-state-in-effect -- carrega a página ao montar.
  useEffect(() => { void load() }, [load])
  // oxlint-disable-next-line react/set-state-in-effect -- sincroniza faturas com o cartão selecionado.
  useEffect(() => { setDetail(null); if (!selectedId) { setInvoices([]); return } api.creditCards.invoices(selectedId).then(setInvoices).catch((requestError) => setError(messageFrom(requestError))) }, [selectedId])

  function openCard(card?: CreditCard) { const value = card ? { name: card.name, credit_limit: card.credit_limit, closing_day: card.closing_day, due_day: card.due_day, payment_account_id: card.payment_account_id, active: card.active } : emptyCard(accounts[0]?.id); setEditing(card ?? null); setCardForm(value); setCardInitial(value); setCardOpen(true) }
  function openPurchase() { const value = emptyPurchase(); value.category_id = categories[0]?.id ?? ''; setPurchaseForm(value); setPurchaseInitial(value); setPurchaseOpen(true) }
  function close(kind: 'card' | 'purchase') { const changed = kind === 'card' ? JSON.stringify(cardForm) !== JSON.stringify(cardInitial) : JSON.stringify(purchaseForm) !== JSON.stringify(purchaseInitial); if (changed) setConfirmExit(kind); else if (kind === 'card') setCardOpen(false); else setPurchaseOpen(false) }
  async function saveCard(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const saved = editing ? await api.creditCards.update(editing.id, cardForm) : await api.creditCards.create(cardForm); setCardOpen(false); await load(); setSelectedId(saved.id) } catch (requestError) { setError(messageFrom(requestError)) } finally { setSaving(false) } }
  async function savePurchase(event: FormEvent) { event.preventDefault(); if (!selected) return; setSaving(true); setError(null); try { await api.creditCards.purchase(selected.id, purchaseForm); setPurchaseOpen(false); await load(); setSelectedId(selected.id); setInvoices(await api.creditCards.invoices(selected.id)) } catch (requestError) { setError(messageFrom(requestError)) } finally { setSaving(false) } }
  async function showInvoice(invoice: CardInvoice) { try { setDetail(await api.creditCards.invoice(invoice.card_id, invoice.reference_month.slice(0, 7))) } catch (requestError) { setError(messageFrom(requestError)) } }
  async function confirmInvoiceAction() { if (!invoiceAction) return; setSaving(true); setError(null); const { kind, invoice } = invoiceAction; const month = invoice.reference_month.slice(0, 7); try { if (kind === 'close') await api.creditCards.closeInvoice(invoice.card_id, month); else await api.creditCards.payInvoice(invoice.card_id, month, today()); setInvoiceAction(null); setDetail(null); await load(); setSelectedId(invoice.card_id); setInvoices(await api.creditCards.invoices(invoice.card_id)) } catch (requestError) { setError(messageFrom(requestError)); setInvoiceAction(null) } finally { setSaving(false) } }

  return <>
    <header className="topbar accounts-header"><div><p className="eyebrow">CRÉDITO</p><h1>Cartões e faturas</h1><p className="subtitle">Acompanhe limites e parcelas sem descontar compras da conta antes do pagamento.</p></div><button className="primary-button" type="button" onClick={() => openCard()}><span>＋</span> Novo cartão</button></header>
    {error && <section className="error-state" role="alert"><div><strong>Não foi possível concluir a operação</strong><p>{error}</p></div><button type="button" onClick={() => setError(null)}>Fechar</button></section>}
    {loading ? <section className="account-grid account-loading"><i /><i /></section> : cards.length ? <section className="card-layout"><div className="credit-card-list">{cards.map((card) => { const available = card.available_limit ?? card.credit_limit; const used = Math.max(0, card.credit_limit - available); return <button type="button" className={`credit-card ${selectedId === card.id ? 'selected' : ''}`} key={card.id} onClick={() => setSelectedId(card.id)}><span className="card-chip" /><span className="card-status">{card.active ? 'Ativo' : 'Inativo'}</span><strong>{card.name}</strong><small>Disponível</small><b>{currency.format(available)}</b><div className="limit-track"><i style={{ width: `${Math.min(100, used / card.credit_limit * 100)}%` }} /></div><footer><span>Fecha dia {card.closing_day}</span><span>Vence dia {card.due_day}</span></footer></button>})}</div>
      {selected && <section className="invoice-panel"><div className="invoice-heading"><div><p className="eyebrow">FATURAS</p><h2>{selected.name}</h2><p>Limite total {currency.format(selected.credit_limit)}</p></div><div><button className="secondary-button" type="button" onClick={() => openCard(selected)}>Editar</button><button className="primary-button" disabled={!selected.active} type="button" onClick={openPurchase}>Nova compra</button></div></div>{invoices.length ? <div className="invoice-list">{invoices.map((invoice) => <div className="invoice-row" key={invoice.id}><button className="invoice-main" type="button" onClick={() => void showInvoice(invoice)}><div><strong>{monthName(invoice.reference_month)}</strong><small>Vence {dateFormat.format(new Date(`${invoice.due_date}T12:00:00`))}</small></div><b>{currency.format(invoice.total)}</b><span className={`invoice-status status-${invoice.status.toLowerCase()}`}>{invoice.status}</span></button>{invoice.status === 'Aberta' && invoice.closing_date <= today() && <button className="invoice-action" type="button" onClick={() => setInvoiceAction({ kind: 'close', invoice })}>Fechar</button>}{invoice.status === 'Fechada' && <button className="invoice-action pay" type="button" onClick={() => setInvoiceAction({ kind: 'pay', invoice })}>Confirmar pagamento</button>}</div>)}</div> : <div className="invoice-empty"><span>▤</span><strong>Nenhuma fatura ainda</strong><p>Registre uma compra para projetar as parcelas por mês.</p></div>}</section>}
    </section> : <section className="accounts-empty"><span>▣</span><h2>Cadastre seu primeiro cartão</h2><p>Informe limite, fechamento, vencimento e a conta usada para pagar.</p><button className="primary-button" type="button" onClick={() => openCard()}>Novo cartão</button></section>}

    {cardOpen && <Drawer title={editing ? editing.name : 'Novo cartão'} eyebrow={editing ? 'ATUALIZAÇÃO' : 'CADASTRO'} onClose={() => close('card')}><form onSubmit={(event) => void saveCard(event)}><label>Nome do cartão<input required maxLength={80} value={cardForm.name} onChange={(event) => setCardForm({ ...cardForm, name: event.target.value })} placeholder="Ex.: Cartão principal" /></label><label>Limite<div className="money-input"><span>R$</span><input required min="0.01" step="0.01" type="number" placeholder="0.00" value={cardForm.credit_limit || ''} onChange={(event) => setCardForm({ ...cardForm, credit_limit: Number(event.target.value) })} /></div></label><div className="form-columns"><label>Dia do fechamento<input required min="1" max="31" type="number" value={cardForm.closing_day} onChange={(event) => setCardForm({ ...cardForm, closing_day: Number(event.target.value) })} /></label><label>Dia do vencimento<input required min="1" max="31" type="number" value={cardForm.due_day} onChange={(event) => setCardForm({ ...cardForm, due_day: Number(event.target.value) })} /></label></div><label>Conta de pagamento<select required value={cardForm.payment_account_id} onChange={(event) => setCardForm({ ...cardForm, payment_account_id: event.target.value })}><option value="" disabled>Selecione</option>{accounts.filter((account) => account.type !== 'Cartão').map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label className="checkbox-line"><input type="checkbox" checked={cardForm.active} onChange={(event) => setCardForm({ ...cardForm, active: event.target.checked })} /> Cartão ativo</label><p className="form-note">Compras feitas após o fechamento entram automaticamente na fatura seguinte.</p><Actions saving={saving} onCancel={() => close('card')} label={editing ? 'Salvar alterações' : 'Criar cartão'} /></form></Drawer>}
    {purchaseOpen && selected && <Drawer title="Nova compra" eyebrow={selected.name.toUpperCase()} onClose={() => close('purchase')}><form onSubmit={(event) => void savePurchase(event)}><label>Descrição<input required maxLength={120} value={purchaseForm.description} onChange={(event) => setPurchaseForm({ ...purchaseForm, description: event.target.value })} placeholder="Ex.: Farmácia" /></label><label>Categoria<select required value={purchaseForm.category_id} onChange={(event) => setPurchaseForm({ ...purchaseForm, category_id: event.target.value })}><option value="" disabled>Selecione</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Data da compra<input required type="date" value={purchaseForm.purchase_date} onChange={(event) => setPurchaseForm({ ...purchaseForm, purchase_date: event.target.value })} /></label><div className="form-columns"><label>Valor total<div className="money-input"><span>R$</span><input required min="0.01" step="0.01" type="number" placeholder="0.00" value={purchaseForm.total_amount || ''} onChange={(event) => setPurchaseForm({ ...purchaseForm, total_amount: Number(event.target.value) })} /></div></label><label>Parcelas<input required min="1" max="120" type="number" value={purchaseForm.installments || ''} onChange={(event) => setPurchaseForm({ ...purchaseForm, installments: Number(event.target.value) })} /></label></div><p className="form-note">{purchaseForm.installments > 1 && purchaseForm.total_amount > 0 ? `${purchaseForm.installments} parcelas de aproximadamente ${currency.format(purchaseForm.total_amount / purchaseForm.installments)}. ` : ''}O saldo da conta só será alterado quando a fatura for paga.</p><Actions saving={saving} onCancel={() => close('purchase')} label="Registrar compra" /></form></Drawer>}
    {detail && <div className="drawer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setDetail(null)}><aside className="account-drawer"><div className="drawer-heading"><div><p className="eyebrow">DETALHES DA FATURA</p><h2>{monthName(detail.reference_month)}</h2><p className="subtitle">Total {currency.format(detail.total)}</p></div><button className="close-button" type="button" onClick={() => setDetail(null)}>×</button></div><div className="installment-list">{detail.installments.map((item) => <div key={item.id}><span><strong>{item.description}</strong><small>Parcela {item.number}/{item.total}</small></span><b>{currency.format(item.amount)}</b></div>)}</div></aside></div>}
    {confirmExit && <ConfirmDialog title="Descartar alterações?" message="As informações preenchidas serão perdidas." confirmLabel="Descartar" onCancel={() => setConfirmExit(null)} onConfirm={() => { if (confirmExit === 'card') setCardOpen(false); else setPurchaseOpen(false); setConfirmExit(null) }} />}
    {invoiceAction && <ConfirmDialog title={invoiceAction.kind === 'close' ? 'Fechar esta fatura?' : 'Confirmar pagamento?'} message={invoiceAction.kind === 'close' ? <>A fatura de <strong>{currency.format(invoiceAction.invoice.total)}</strong> não aceitará novas compras após o fechamento.</> : <>Serão debitados <strong>{currency.format(invoiceAction.invoice.total)}</strong> da conta vinculada. A liquidação não será contada como uma segunda despesa.</>} confirmLabel={invoiceAction.kind === 'close' ? 'Fechar fatura' : 'Confirmar pagamento'} busy={saving} onCancel={() => setInvoiceAction(null)} onConfirm={() => void confirmInvoiceAction()} />}
  </>
}

function Drawer({ title, eyebrow, onClose, children }: { title: string; eyebrow: string; onClose: () => void; children: React.ReactNode }) { return <div className="drawer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="account-drawer"><div className="drawer-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button className="close-button" type="button" onClick={onClose}>×</button></div>{children}</aside></div> }
function Actions({ saving, onCancel, label }: { saving: boolean; onCancel: () => void; label: string }) { return <div className="drawer-actions"><button className="secondary-button" type="button" onClick={onCancel}>Cancelar</button><button className="primary-button" disabled={saving} type="submit">{saving ? 'Salvando…' : label}</button></div> }
function monthName(value: string) { const text = new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(new Date(`${value.slice(0, 10)}T12:00:00`)); return text.charAt(0).toUpperCase() + text.slice(1) }
function messageFrom(error: unknown) { return error instanceof Error ? error.message : 'Ocorreu um erro inesperado.' }
